### PR TITLE
Fix running the vis platform behind a reverse proxy

### PR DESCRIPTION
**Pull request by gpeb2**
There are several tasks required to fix issue #1362, they are as follows:

- Update the visualisation code:
  - [ ] ~~Re-add the code to append the `basePath` variable to the paths of images, etc. (@qhouyee).~~
  - [x] Add a custom [image loader](https://nextjs.org/docs/app/api-reference/components/image#loader) to run the [`addBasePath`](https://github.com/vercel/next.js/blob/canary/packages/next/src/client/add-base-path.ts) function on the image paths.
  - [x] Set the custom image loader as the default one for all images by specifying it as the [loader file](https://nextjs.org/docs/app/api-reference/components/image#loaderfile).
  - [ ] Update the documentation to tell developers to use the `<Image>` component.

- Update the `VisualisationService` class in the stack-clients project so that:

  - [ ] the Nginx configuration is correct for NextJS.
  - [ ] it correctly sets the `basePath` variable in the vis container.

### CODE REVIEW

**Review by Ushcode — COMMENTED** [review]
I created issue #1359 and linked branch yesterday for this issue, I will merge it into this branch and then close #1359 and drop the branch.

This should properly allow ASSET_PREFIX env var to prefix any of next's static files (the ones in the .next folder (compiled `.js` and `.css` files) as well as the BASE_PATH to prepend any images or `.md` files that go in the public folder.

**Review by Ushcode — COMMENTED** [review]
the branch i merged in here was taken off another that hadn't been merged to main.. once we merge that I'll rebase so only the relevant changes exist on this PR

**Review by Ushcode — COMMENTED** [review]
the branch i merged in here was taken off another that hadn't been merged to main.. once we merge that I'll rebase so only the relevant changes exist on this PR

**Comment by gpeb2** [comment]
> the branch i merged in here was taken off another that hadn't been merged to main.. once we merge that I'll rebase so only the relevant changes exist on this PR

Merging "main" into this branch once the other one has been merged to "main" will automatically remove the overlapping commits so no need to rebase.

**Review by Ushcode — COMMENTED** [review]
NB lots of changes to augmented-uk folers as well to this branch

**Review by qhouyee — APPROVED** [review]

**Pull request merged**
