### PR TITLE
dev-dtvf 3.2.0

### PR DESCRIPTION
**Pull request by mdhillmancmcl**
This PR requests the merge of the dev-dtvf-3.2.0 branch and brings in the following minor features and bug fixes:

Features:
- Can now create a CesiumTerrainProvider via the `terrain` variable in the `settings.json` file. 
- Can now add custom attribution HTML content via the `attribution` variable in the `settings.json` file.
- Can now control globe translucency for Cesium visualisations

Fixes:
- Commented out erroneous calls to search components when collapsing the side panel.

Misc:
- Updated READMEs and GitHub wiki pages

### CODE REVIEW

**Comment by sm453** [comment]
Sorry, I can't see any changes on the wiki - it still shows v3.1.0 as the latest version.

**Comment by sm453** [comment]
Could you please add something to the readme file(s) about how to use the custom attributions?

**Comment by sm453** [comment]
Just changing the version of dtvf.min.js and css in a working index.html from 3.1 to 3.2 (i.e. without putting a terrain into the settings file) breaks the whole thing - it produces tons of errors such as this one:
`GET https://api.mapbox.com/styles/v1/mapbox/dark-v10/tiles/256/13/4267/2804?access_token= 401 (Unauthorized)`

**Comment by mdhillmancmcl** [comment]
> Sorry, I can't see any changes on the wiki - it still shows v3.1.0 as the latest version.

My mistake, updated this now.

**Comment by mdhillmancmcl** [comment]
> Could you please add something to the readme file(s) about how to use the custom attributions?

This is detailed on the Advanced Features page of the wiki. I have however updated the READMEs to explicity mention this feature and link to its section on the aforementioned page.

**Comment by mdhillmancmcl** [comment]
> Just changing the version of dtvf.min.js and css in a working index.html from 3.1 to 3.2 (i.e. without putting a terrain into the settings file) breaks the whole thing - it produces tons of errors such as this one: `GET https://api.mapbox.com/styles/v1/mapbox/dark-v10/tiles/256/13/4267/2804?access_token= 401 (Unauthorized)`

This is not something I can reproduce, but it appears that the Mapbox API token isn't being set correctly. Could you send over the files you used when seeing this error please @sm453?

**Comment by sm453** [comment]
> > Just changing the version of dtvf.min.js and css in a working index.html from 3.1 to 3.2 (i.e. without putting a terrain into the settings file) breaks the whole thing - it produces tons of errors such as this one: `GET https://api.mapbox.com/styles/v1/mapbox/dark-v10/tiles/256/13/4267/2804?access_token= 401 (Unauthorized)`
> 
> This is not something I can reproduce, but it appears that the Mapbox API token isn't being set correctly. Could you send over the files you used when seeing this error please @sm453?
I am now no longer able to reproduce this myself. It seems to be working now.

**Comment by sm453** [comment]
I have tested the translucency feature. It works, however I believe this quantity is an opacity, because it behaves as such (1=fully opaque, 0=fully see-through). NB translucency = 1-opacity. Can you please change the name? (That way it would also be consistent with other tools such as QGIS.)

**Review by sm453 — APPROVED** [review]
All tested - works.

**Pull request merged**
