### PR TITLE
133 dev design of experiment

### PR DESCRIPTION
**Pull request by jb2197**
DoE Agent for automated design of experiment exercise.

### CODE REVIEW

**Comment by sm453** [comment]
The DoE agent readme gives an example of an instance IRI as:
"https://github.com/cambridge-cares/TheWorldAvatar/blob/develop/JPS_Ontology/ontology/ontoderivation/OntoDerivation.owl#derivede72edb7e-d0ac-429d-9557-257d3e31d92b"
This does not look like a good IRI for an instance to me. Surely we're not hosting any KG instances on GitHub, and surely not as part of a TBox OWL file?

**Comment by sm453** [comment]
The DoE agent readme gives an example of an instance IRI as:
"https://github.com/cambridge-cares/TheWorldAvatar/blob/develop/JPS_Ontology/ontology/ontoderivation/OntoDerivation.owl#derivede72edb7e-d0ac-429d-9557-257d3e31d92b"
This does not look like a good IRI for an instance to me. Surely we're not hosting any KG instances on GitHub, and surely not as part of a TBox OWL file?

**Comment by jb2197** [comment]
> The DoE agent readme gives an example of an instance IRI as: "https://github.com/cambridge-cares/TheWorldAvatar/blob/develop/JPS_Ontology/ontology/ontoderivation/OntoDerivation.owl#derivede72edb7e-d0ac-429d-9557-257d3e31d92b" This does not look like a good IRI for an instance to me. Surely we're not hosting any KG instances on GitHub, and surely not as part of a TBox OWL file?

I think this is related to the fact we used namespace of OntoDerivation when creating derivation instances, for example the unique identifier of a derivation instance is defined as: 
`String derivedQuantity = derivednamespace + "derived" + UUID.randomUUID().toString();` 
(https://github.com/cambridge-cares/TheWorldAvatar/blob/develop/JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/derivation/DerivationSparql.java#L110)

The `derivednamespace` is defined at https://github.com/cambridge-cares/TheWorldAvatar/blob/develop/JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/derivation/DerivationSparql.java#L49

Would the below prefix be a better choice when generating `derivedQuantity`?
`https://theworldavatar.com/kb/ontoderivation/`

**Comment by sm453** [comment]
"https://theworldavatar.com/kb/ontoderivation/" wouldn't be much better either, mainly because we've decided not to use "kb" any more going forward. In the readme, we're looking for an example, so how about "https://www.example.com/triplestore/repository/"?

**Comment by sm453** [comment]
While we're on the subject of "/kb/" in worldavatar URLs, please remove all such occurrences in the URLs in the readme file. This is obsolete, and we do not want to encourage people to stick to this outdated practice.

**Comment by sm453** [comment]
Given the parallel developments of asynchronous Python agents, is some code e.g. in the summit app now obsolete?

**Comment by jb2197** [comment]
> "https://theworldavatar.com/kb/ontoderivation/" wouldn't be much better either, mainly because we've decided not to use "kb" any more going forward. In the readme, we're looking for an example, so how about "https://www.example.com/triplestore/repository/"?

> While we're on the subject of "/kb/" in worldavatar URLs, please remove all such occurrences in the URLs in the readme file. This is obsolete, and we do not want to encourage people to stick to this outdated practice.

> Given the parallel developments of asynchronous Python agents, is some code e.g. in the summit app now obsolete?


All above issues will be addressed when updating the DoE agent based on the asynchronous python agent that is to be released in TestPyPI soon.

**Comment by sm453** [comment]
Actually, the "/kb/" in URLs issue is not just limited to the readme file. Please check all files, code or otherwise.

**Comment by sm453** [comment]
I guess once #91 is merged to develop, and then into this branch, the current changes to the derivation client and sparql java files will be superseded, correct?

**Comment by jb2197** [comment]
> Actually, the "/kb/" in URLs issue is not just limited to the readme file. Please check all files, code or otherwise.

Sure, I will remove all appearance of /kb/.

**Comment by jb2197** [comment]
> I guess once #91 is merged to develop, and then into this branch, the current changes to the derivation client and sparql java files will be superseded, correct?

I don't think we changed anything in DerivationClient/DerivationSparql java files specifically for DoE Agent (i.e., this PR), all the codes related to derivation in this PR were interfaced via py4jps. As we discussed, those codes (mostly monitorDerivations in app.py) will be moved to a standalone asynchronous python agent package, which will be released as TestPyPI installable and consequently be used in the following development of DoEAgent and other agents. So I think we can avoid any direct interaction between python agents and DerivationClient/DerivationSparql java files - if we want to make any changes/add any new features, we just need to update the standalone asynchronous python agent package and all the changes will be made available to python agents via re-installing from PyPI.

**Comment by jb2197** [comment]
> > I guess once #91 is merged to develop, and then into this branch, the current changes to the derivation client and sparql java files will be superseded, correct?
> 
> I don't think we changed anything in DerivationClient/DerivationSparql java files specifically for DoE Agent (i.e., this PR), all the codes related to derivation in this PR were interfaced via py4jps. As we discussed, those codes (mostly monitorDerivations in app.py) will be moved to a standalone asynchronous python agent package, which will be released as TestPyPI installable and consequently be used in the following development of DoEAgent and other agents. So I think we can avoid any direct interaction between python agents and DerivationClient/DerivationSparql java files - if we want to make any changes/add any new features, we just need to update the standalone asynchronous python agent package and all the changes will be made available to python agents via re-installing from PyPI.

@sm453 actually you are right, I just checked we previously merged branch 135-dev-expand-derivation-framework (https://github.com/cambridge-cares/TheWorldAvatar/pull/68) into this PR. So yes, these changes will be updated with the most updated codes, but as we will go with releasing the standalone asynchronous python agent package in PyPI, any of these changes won't directly affect the DoE agent.

**Comment by jb2197** [comment]
> > Actually, the "/kb/" in URLs issue is not just limited to the readme file. Please check all files, code or otherwise.
> 
> Sure, I will remove all appearance of /kb/.

This is done in commit https://github.com/cambridge-cares/TheWorldAvatar/pull/69/commits/9df4a39c8927762c229adacf6b10d7c39211b097.

**Review by sm453 — APPROVED** [review]

**Review by sm453 — APPROVED** [review]

**Pull request merged**
