### PR TITLE
Fixes for TWA-VF

### PR DESCRIPTION
**Pull request by mdhillman**
This PR brings in bug fixes for issues #534, #770, #301, and #878. The former three will need to be tested within Mapbox and Cesium visualisations (using the example ones are fine).

Update: this PR has been updated to include the following changes:
* Updated mouse handling for feature popups.
* Automated action now pushes image with more tags.
* Added null check for possible missing `layers` object when toggling Cesium layers.
* Minor update to build script for local development.

> [!WARNING]
> Note that just before this PR is merged, the version of the TWA-VF will need the "-SNAPSHOT" token removed. In fact, the automated checks *should* fail until this is done.

> [!WARNING]
> Depending on when this PR is approved, and when related PRs are approved, the specific version number may need adjusting.

### CODE REVIEW

**Comment by mdhillman** [comment]
Converting to draft whilst I look into some further fixes.

**Review by cmclscourtney — CHANGES_REQUESTED** [review]
- [ ] #534 Might be worth doing multiple wraps on title text for such an edge case as below.  
- [x] #534 Also should popups should go above (or to the side of) icon if would be blocked by screen
Capture

The following are some quality of life things that would be useful for ongoing development
- [x] Would be useful if each SNAPSHOT image version was pushed with a unique branch identifier to make testing easier and make sure there isn't overlap in branch names.
- [ ] A branch per issue fix would be make things easier I think but am aware you might be unwilling to spam minor versions.

**Comment by mdhillman** [comment]
Updates following feedback:

* Image for this branch now includes branch name (ghcr.io/cambridge-cares/twa-vf:4.0.1-fix-twa-vf-4.0.1-SNAPSHOT).
* Scripts to run examples now default to use current version (i.e. that defined in library/VERSION file).
* Popup placement now adjusts at edges of maps.
* Popup content now gets multiple line wraps (if needed).
* Popup descriptions now cut off after 250 characters.

**Comment by mdhillman** [comment]
I am unable to reproduce Seb's popup issue using the Cesium example. 

I can try to run Seb's use case (if it's simple to spin up locally), or ask Chung (who's also working with Cesium at the moment) to try it on his data.

**Comment by mdhillman** [comment]
> I am unable to reproduce Seb's popup issue using the Cesium example.
> 
> I can try to run Seb's use case (if it's simple to spin up locally), or ask Chung (who's also working with Cesium at the moment) to try it on his data.

We have tried this on Chung's machine, with his Cesium data and cannot reproduce it. Later today I will try on a monitor with lower resolution, and perhaps with different Windows scaling options.

**Comment by mdhillman** [comment]
This PR now closes #928.

**Comment by mdhillman** [comment]
> > I am unable to reproduce Seb's popup issue using the Cesium example.
> > I can try to run Seb's use case (if it's simple to spin up locally), or ask Chung (who's also working with Cesium at the moment) to try it on his data.
> 
> We have tried this on Chung's machine, with his Cesium data and cannot reproduce it. Later today I will try on a monitor with lower resolution, and perhaps with different Windows scaling options.

Have now tried on HD and 4K screens, with 100%, 125%, and 150% windows scaling. Can still not reproduce the issue :(

**Comment by mdhillman** [comment]
I have updated the feature-picking routine that is used to determine the currently hovered WMS feature in Cesium visualisations. This appears to resolve the popup placement issue experienced by @sm453.

Note that Cesium WMS feature interaction is asynchronous and can be a little slow. In testing this only causes issues if you rapidly move the mouse (so I suggest not doing that).

Updated docker image is `ghcr.io/cambridge-cares/twa-vf:4.0.1-fix-twa-vf-4.0.1-SNAPSHOT`

**Comment by mdhillman** [comment]
> You're right, it's slow (and not very accurate in determining the contents), but at least the placement is correct. Good enough for now.

This is unfortunately another effect of Cesium not supporting vector data via WMS. With raster data, to get _any_ information, another request has to be made to the server. This causes a delay, which in turn causes issues if you've moved the mouse during that delay.

I have some thoughts on improving in in future, but I struggle to see how we could make it as seamless as it is with the vector data on Mapbox.

**Review by cmclscourtney — APPROVED** [review]

**Pull request merged**
