### PR TITLE
376-error-thrown-when-trying-to-query-raster-data-in-the-stack

### PR DESCRIPTION
**Pull request by gpeb2**
Changed the command to set the "postgis.enable_outdb_rasters" and "postgis.gdal_enabled_drivers" properties when uploading a raster to the PostGIS database. Previously it was only setting it for the session, now it sets it permanently for the database. This should fix issue #376 .

### CODE REVIEW

**Review by markushofmeister — COMMENTED** [review]
Changes look appropriate to me (i.e. very similar to the settings I needed to apply to get raster handling working in my local PostGis). However, I am unable to spin up the stack from `Deploy\stacks\dynamic\stack-manager` using the established `bash ./stack.sh start RASTER-TEST` on this branch `376-error-thrown-when-trying-to-query-raster-data-in-the-stack`.
Initially I thought that might be due to having another stack running (i.e. on Digital Ocean), but the same problem persists on my local machine (i.e. without other stack running).

Is that expected? If so, please elaborate how I could best test the functionality?
Btw, as I will use the data uploader to upload some test raster data for this: Is there a data uploader functionality for Ontop mappings?

**Comment by gpeb2** [comment]
> Changes look appropriate to me (i.e. very similar to the settings I needed to apply to get raster handling working in my local PostGis). However, I am unable to spin up the stack from `Deploy\stacks\dynamic\stack-manager` using the established `bash ./stack.sh start RASTER-TEST` on this branch `376-error-thrown-when-trying-to-query-raster-data-in-the-stack`. Initially I thought that might be due to having another stack running (i.e. on Digital Ocean), but the same problem persists on my local machine (i.e. without other stack running).

You might need to explicitly add an external port number i.e. `bash ./stack.sh start RASTER-TEST 3840`
> 
> Is that expected? If so, please elaborate how I could best test the functionality? Btw, as I will use the data uploader to upload some test raster data for this: Is there a data uploader functionality for Ontop mappings?

Yes, it's described in step 5 of the uploader documentation, https://github.com/cambridge-cares/TheWorldAvatar/blob/cfdc2d48fbfd7530e797d62fba10905a13a9722d/Deploy/stacks/dynamic/stack-data-uploader/README.md

**Review by kokfoongcmcl — APPROVED** [review]
Tested with CReDo phase 1

**Review by markushofmeister — APPROVED** [review]
Tested with OpenPopGrid .asc raster data and also successfully tested querying geospatial sum via Ontop mapping.

**Pull request merged**
