### PR TITLE
Dev create emission agent

### PR DESCRIPTION
**Pull request by markushofmeister**
This derivation agent converts the `ConsumedGasAmount`s and `ProvidedHeatAmount`s (as instantiated by the District Heating Optimisation Agent) into associated `Emission` instances according to OntoDispersion. 
The emission estimation is based on literature values for waste incineration and natural gas combustion. The corresponding excel sheet can be found [here](https://www.dropbox.com/scl/fi/wj9d8kzt6xfremrgs0ful/20230824-Emissions_Calculations.xlsx?rlkey=uifhiv2nq98tg5nn7wx4uv4o5&dl=0).

Further resources (if relevant):
[Target Derivation cascade design](https://lucid.app/lucidchart/9fabc350-143b-4ca3-be52-b174c9f82c07/view?invitationId=inv_46624da8-91ef-4def-adf7-47eec515c77e&page=0_0#)
[District Heating MIRO board](https://miro.com/app/board/uXjVOhnB9_4=/)

### CODE REVIEW

**Comment by kok-foong** [comment]
Can you commit the .vscode configurations?

**Comment by markushofmeister** [comment]
> Can you commit the .vscode configurations?

Added with commit [aae4ef3](https://github.com/cambridge-cares/TheWorldAvatar/pull/887/commits/aae4ef30da2ba6b2130a0873db4e3d36098ce6ca)

**Review by kok-foong — DISMISSED** [review]
Only checked the triples created by the agent, look fine and should work with the AERMOD agent

**Review by kok-foong — CHANGES_REQUESTED** [review]
the pollutant instance should be as following:
emission disp:hasPollutantID disp:abc;
disp:abc rdf:type disp:PM10.

**Comment by markushofmeister** [comment]
> the pollutant instance should be as following: emission disp:hasPollutantID disp:abc; disp:abc rdf:type disp:PM10.

Addressed by commit [8208330](https://github.com/cambridge-cares/TheWorldAvatar/pull/887/commits/8208330a5ff0409ec4163508086d2a8b9de3af2b)

**Comment by markushofmeister** [comment]
I updated the instantiation of the pollutant types. @kok-foong: Can you please re-verify the compliance with Aermod now?

**Review by kok-foong — APPROVED** [review]

**Pull request merged**
