### PR TITLE
Dev dockerise forecasting agent

### PR DESCRIPTION
**Pull request by markushofmeister**
This PR dockerises the initial version of the Forecasting Agent and provides functionality to easily deploy it to a stack. Tests have been refactored and now use testcontianers.

Closes issue #498

### CODE REVIEW

**Comment by markushofmeister** [comment]
Further improvements of the agent shall be addressed by issues #528, #529, #530

**Comment by sm453** [comment]
`docker.cmclinnovations.com/stack-client:1.6.2` is now available. Please update the relevant places where this is referenced.

**Comment by sm453** [comment]
Do you really need a root-level `__init__.py`? If your code is a Python package with a root-level `setup.py`, then this shouldn't be necessary.

**Comment by markushofmeister** [comment]
> `docker.cmclinnovations.com/stack-client:1.6.2` is now available. Please update the relevant places where this is referenced.

Addressed by [90fdd49](https://github.com/cambridge-cares/TheWorldAvatar/pull/521/commits/90fdd49960f86ec7971b26b6317eaa41e262c929)

**Comment by markushofmeister** [comment]
> Do you really need a root-level `__init__.py`? If your code is a Python package with a root-level `setup.py`, then this shouldn't be necessary.

I believe this got accidentally added and removed in commit [66adb1a](https://github.com/cambridge-cares/TheWorldAvatar/pull/521/commits/66adb1a383a4aecc70fdee759c5390db4990575b)

**Review by sm453 — APPROVED** [review]
Tested, works.

Issue #570 about the design of the database/namespace specification has been posted separately.

**Pull request merged**
