### PR TITLE
Spin up a separate Ontop container for each Postgresql database

### PR DESCRIPTION
**Pull request by gpeb2**
Ontop can only map to one database but it is often benificial to put different datasets in their own databases. These changes cause the stack-data-uploader to spin up a new Ontop container if a dataset includes an Ontop maping file.

### CODE REVIEW

**Review by cmclscourtney — CHANGES_REQUESTED** [review]
Reviewed code and tested. All looks good on that front. 

Would be good to add something to the documentation on this. These few issues would be worth noting.
- [ ] New UI endpoints 
- [ ] New internal endpoints that are created.
- [ ] ```postgres``` database uses default ontop.

**Comment by gpeb2** [comment]
I've updated the FeatureInfoAgent so that it is now possible to use placeholders like ```[ONTOP-<dataset name>]``` (case-insensitive) after the ```SERVICE``` keyword to direct subqueries to a particular Ontop container. For example ```SERVICE [ontop-pirmasens]```.
@cmclscourtney and @YiKaiTsai, please can you test this works for you?

**Comment by YiKaiTsai** [comment]
Was not able to successfully query from Ontop endpoint when spinning up FeatureInfoAgent (FIA) or querying from Blazegraph. Details are as follows:

1) FIA did not work when using placeholder ```[ONTOP-datasetName]```. When checking the log, the SPARQL that FIA tried was
```
select distinct ?class {
         SERVICE <http://stackName-ontop:8080/sparql/> { <iri> a ?x . }
         ?x rdfs:subClassOf* ?class .
         ?class rdf:type owl:Class .
}
```

It seems that the placeholder did not get properly converted to SERVICE IRI ```<stackName-ontop-datasetName:8080/sparql>```.

2) Using SERVICE IRI ```<stackName-ontop-datasetName:8080/sparql>``` inside Blazegraph did not work. The error was ```java.util.concurrent.ExecutionException: java.net.UnknownHostException: stackName-ontop-datasetName: Name or service not known```.

**Comment by gpeb2** [comment]
This should also close issue #601.

**Review by cmclscourtney — APPROVED** [review]

**Pull request merged**
