### PR TITLE
150 dev fix ontokin and ontospecies

### PR DESCRIPTION
**Pull request by jb2197**
Changes introduced in this fix:

(1) Triples in OntoKin TBox CSV:

- removed `<OntoKin:Species> <equivalent-to> <OntoCAPE:ChemicalSpecies>`
- removed `<OntoKin:Species> <OntoKin:hasUniqueSpeciesIRI> <xsd:string>`
- added `<OntoKin:Species> <OntoSpecies:hasUniqueSpecies> <OntoSpecies:Species>`

(2) Triples in OntoSpecies TBox CSV: 

- added `<OntoSpecies:Species> <equivalent-to> <OntoCAPE:ChemicalSpecies>`
- added `<OntoSpecies:Species> <rdfs:subClassOf> <OntoKin:Species>`
- removed `<gc:Atom> <gc:hasAtomCoordinateX> <OntoSpecies:StringValue>`
- removed `<gc:Atom> <gc:hasAtomCoordinateY> <OntoSpecies:StringValue>`
- removed `<gc:Atom> <gc:hasAtomCoordinateZ> <OntoSpecies:StringValue>`
- added `<gc:Atom> <gc:hasAtomCoordinateX> <gc:FloatValue>`
- added `<gc:Atom> <gc:hasAtomCoordinateY> <gc:FloatValue>`
- added `<gc:Atom> <gc:hasAtomCoordinateZ> <gc:FloatValue>`
- fixed typo of "ontokin.owl" in the namespace of some appearances of `<OntoKin:ElementNumber>`

(3) Re-generated OntoSpecies and OntoKin based on above changes, it should be noted that the difference of OntoSpecies file between this version and its previous version is rather large as the previous version of OntoSpecies.owl was not fully reflecting the triples defined in the previous version of the ontospecies.csv file. The ontospecies.csv file presented in this fix is confirmed by @msff2, @dln22, and @am2145 to be the most updated version and it contains all the correct declarations they wanted to introduce. The re-generated OWL files should thus be up-to-date and correct.

### CODE REVIEW

**Comment by jb2197** [comment]
It just occurred to me that the data property currently been used in the OntoSpecies ABoxes related to OntoSpecies:PubChemCID and OntoSpecies:SpinMultiplicity are actually lowerCamelCase:
`<OntoSpecies:Species> <OntoSpecies:pubChemCID> <xsd:string>`
`<OntoSpecies:Species> <OntoSpecies:spinMultiplicity> <xsd:string>`

Maybe worth updating the record in TBox instead of updating all ABoxes (130 appearances for each data property)?

**Comment by sm453** [comment]
> It just occurred to me that the data property currently been used in the OntoSpecies ABoxes related to OntoSpecies:PubChemCID and OntoSpecies:SpinMultiplicity are actually lowerCamelCase: `<OntoSpecies:Species> <OntoSpecies:pubChemCID> <xsd:string>` `<OntoSpecies:Species> <OntoSpecies:spinMultiplicity> <xsd:string>`
> 
> Maybe worth updating the record in TBox instead of updating all ABoxes (130 appearances for each data property)?

Properties should be in lowerCamelCase - I believe this is the standard convention. To me this suggests that the ABoxes are correct and that the TBox should be updated.

**Review by am2145 — CHANGES_REQUESTED** [review]
As an additional note, the StringValue data types for the hasAtomCoordinate object properties in OntoSpecies has been changed to FloatValue to be consistent with the current OntoSpecies OWL and instances on blazegraph. 

As mentioned by Jiaru, the current instances use lower case pubChemCID and spinMultiplicity. We should change this in the OntoSpecies TBox CSV and OWL files to follow this.

**Comment by jb2197** [comment]
> > It just occurred to me that the data property currently been used in the OntoSpecies ABoxes related to OntoSpecies:PubChemCID and OntoSpecies:SpinMultiplicity are actually lowerCamelCase: `<OntoSpecies:Species> <OntoSpecies:pubChemCID> <xsd:string>` `<OntoSpecies:Species> <OntoSpecies:spinMultiplicity> <xsd:string>`
> > Maybe worth updating the record in TBox instead of updating all ABoxes (130 appearances for each data property)?
> 
> Properties should be in lowerCamelCase - I believe this is the standard convention. To me this suggests that the ABoxes are correct and that the TBox should be updated.


> As mentioned by Jiaru, the current instances use lower case pubChemCID and spinMultiplicity. We should change this in the OntoSpecies TBox CSV and OWL files to follow this.


The requested changes are made in the last commit and please have a look if you are happy with the rest of the PR. Thanks.

**Review by sm453 — APPROVED** [review]

**Review by am2145 — APPROVED** [review]
The pubChemCID and spinMultiplicity properties have been changed to lower case as was discussed. The Species class declarations and equivalencies also look correct. I believe the changes can be approved.

**Review by msff2 — COMMENTED** [review]
All changes seem fine and correctly done.

**Pull request merged**
