### PR TITLE
Ability to upload triples through the stack data uploader

### PR DESCRIPTION
**Pull request by gpeb2**
Closes issues #272 and #330.

### CODE REVIEW

**Comment by gpeb2** [comment]
@markushofmeister or @kokfoongcmcl can one of you please test that these changes resolve issues #272 and #330 and approve the pull request if they do?

**Comment by kokfoongcmcl** [comment]
Can you add an example in the example datasets?

**Review by markushofmeister — CHANGES_REQUESTED** [review]
I *only* tested uploading RDF data  and *not* running larger queries/updates yet.

I can confirm that the `stack-data-uploader` is able to upload triples; however, I highly doubt the correctness of the upload. I used the following `config` file to upload a `.nt` file of 619,325 triples. After the upload finished, the newly created namespace, however, contains 1,073,298 triples. The uploaded data contains multiple blank nodes and also connections which do not exist in the initial upload data. See the attached screenshot for an example (left: initial data, right: data after re-import).

`
{
    "namespace": "buildings_test",
    "datasetDirectory": "triples",
    "dataSubsets": [
        {
            "type": "Triples",
            "skip": false
        }
    ]
}
`
image


Furthermore, the logs of the `stack-data-uploader` contain the following exception message although all other data sets have been flagged as to be skipped for this upload:

`
Exception in thread "main" java.lang.RuntimeException: Failed to write out combined Ontop mapping file '/ontop.obda'.
        at com.cmclinnovations.stack.clients.ontop.OntopClient.updateOBDA(OntopClient.java:65)
        at com.cmclinnovations.stack.clients.core.datasets.Dataset.lambda$loadData$2(Dataset.java:107)
        at java.base/java.util.ArrayList.forEach(Unknown Source)
        at com.cmclinnovations.stack.clients.core.datasets.Dataset.loadData(Dataset.java:107)
        at java.base/java.util.LinkedHashMap$LinkedKeySet.forEach(Unknown Source)
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Unknown Source)
        at com.cmclinnovations.stack.clients.core.StackClient.uploadInputDatasets(StackClient.java:97)
        at com.cmclinnovations.stack.DataUploader.main(DataUploader.java:12)
Caused by: java.nio.file.AccessDeniedException: /tmp/ontop1404986076460725709.obda
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
        at java.base/java.nio.file.Files.newOutputStream(Unknown Source)
        at com.cmclinnovations.stack.clients.ontop.OntopClient.updateOBDA(OntopClient.java:46)
`

Further remarks:
1) As suggested by Kok Foong, some "official" documentation would help
2) If we want to support quads (which I think we should!), renaming `"type": "Triples"` to something more generic, e.g. `"type": "RDF"` might help to avoid ambiguity
3) If I remember correctly, for triples a stated namespace will be created if it does not already exist. For quads this behaviour is different and the namespace would need to be created manually beforehand. Is that still correct? If so, it might be worth to either align the behaviour (i.e. create also a non-existing quad namespace automatically - I do have a code snippet for that if you need) or at least highlight that behaviour clearly in the documentation.

**Comment by gpeb2** [comment]
A summary of things to add, check, or change and any comments:

- [ ] Add an example data set that contains RDF files.
- [ ] Check that the RDF data is being uploaded correctly (I'm just using the ```RemoteStoreClient``` so I'm not sure where any extra triples might be coming from). @markushofmeister can you send me the ```.nt``` file?
- [ ] Look into "skip" issue, I can't reproduce this. @markushofmeister can you send me your .json config files so I can try to reproduce this, I don't think I'll need the data or OBDA files.
- [ ] Add instructions for this functionality to the documentation (I've started updating the pre-triple documentation and want to get that merged before adding this).
- [ ] I've updated the code so that the types "Triples", "triples", "RDF" and "rdf" all map to the same class internally although the documentation will only mention "rdf" (I am also changing the other types so that the fully lowercase versions are accepted and the norm in the documentation and examples)
- [ ] Add support for user-defined properties when creating new namespaces in Blazegraph.

**Comment by markushofmeister** [comment]
> A summary of things to add, check, or change and any comments:
> 
> * [ ]  1) Add an example data set that contains RDF files.
> * [ ]  2) Check that the RDF data is being uploaded correctly (I'm just using the `RemoteStoreClient` so I'm not sure where any extra triples might be coming from). @markushofmeister can you send me the `.nt` file?
> * [ ]  3 )Look into "skip" issue, I can't reproduce this. @markushofmeister can you send me your .json config files so I can try to reproduce this, I don't think I'll need the data or OBDA files.
> * [ ]  4) Add instructions for this functionality to the documentation (I've started updating the pre-triple documentation and want to get that merged before adding this).
> * [ ]  5) I've updated the code so that the types "Triples", "triples", "RDF" and "rdf" all map to the same class internally although the documentation will only mention "rdf" (I am also changing the other types so that the fully lowercase versions are accepted and the norm in the documentation and examples)
> * [ ]  6) Add support for user-defined properties when creating new namespaces in Blazegraph.

**re 5)** The type `rdf` does (still) not work for me even after pulling the latest stack-data-uploader image (created 2022-10-19T13:05Z"). 
```
InvalidTypeIdException: Could not resolve type id 'rdf' as a subtype of `com.cmclinnovations.stack.clients.core.datasets.DataSubset`: known type ids = [Raster, Tabular, Triples, Vector, raster, tabular, triples, vector]
```

**re 3)** The issue remains. Please find a screenshot of my `config` files as well as input data structure below. In case you cannot spot anything obviously wrong, happy to share the files. I thought I followed the [latest guidlines](https://github.com/cambridge-cares/TheWorldAvatar/blob/cfdc2d48fbfd7530e797d62fba10905a13a9722d/Deploy/stacks/dynamic/stack-data-uploader/README.md) in the Stack Data Uploader Readme correctly.
image

**re 2)** I believe this issue is again related to NGINX. I just retried uploading the `.nt` file from my local machine (i.e. script running outside the stack) via 1) Python's SPARQLWrapper package as well as 2) using the wrapped `RemoteStoreClient.uploadFile` [method](https://github.com/cambridge-cares/TheWorldAvatar/blob/dev-EPCInstantiationAgent/Agents/EnergyPerformanceCertificateAgent/epcdata/kgutils/initialise_ocgml.py) (actually, this is what I used to upload the OntoCityGml quads data initially). Both work and create the correct number of triples uploaded. However, 2) only works if the specified SPARQL endpoint is outside the stack (i.e. in that case a separately spun up Blazegraph container) as I get again a `413` (i.e. request too large) exception if using a SPARQL endpoint from Blazegrapoh running in the stack.
Let me know if you still need the `.nt` file to test

**Comment by kokfoongcmcl** [comment]
Do we also want to add the ability to take in CSV input files for the TBox generator?

**Comment by kokfoongcmcl** [comment]
Don't really have a strong opinion about this, but I'm concerned about using very Blazegraph specific properties in the config files and the lack of documentation on those properties

**Comment by gpeb2** [comment]
> Do we also want to add the ability to take in CSV input files for the TBox generator?

This will be added in a separate pull request. There is an issue for uploading both A-boxes and T-boxes from CSV files #273.

**Comment by gpeb2** [comment]
> Don't really have a strong opinion about this, but I'm concerned about using very Blazegraph specific properties in the config files and the lack of documentation on those properties

Whilst this is using Blazegraph classes to do this I think it is using the SAIL interface so should work with other triplestores.

Regarding the actual properties, I think this is the best we can do, some of them are generic SAIL properties but most control Blazegraph specific settings.

On the documentation of these, I have provided links to some of the documentation that is available. We could generate a table in this README to document them in a single location. Another option would be to add a separate layer over the top where we define more user friendly settings that get translated before being sent to the triplestore.

**Comment by markushofmeister** [comment]
I am unable to start the `stack-data-uploader`. I followed the README to create a new stack for testing purposes on the Digital Ocean machine (which currently has another stack running called `KINGS-LYNN` at port 3838).
I executed `dynamic/stack-manager$ ./stack.sh start TEST 3840` to start the stack and then `dynamic/stack-data-uploader$ ./stack.sh start TEST` to test the data upload.

The uploader fails with the following message
```
docker.cmclinnovations.com/blazegraph:1.0.0-SNAPSHOT
docker.cmclinnovations.com/geoserver:2.20.4
WARN[0000] The "IMAGE_SUFFIX" variable is not set. Defaulting to a blank string. 
Error: No such service: TEST_stack-data-uploader
Ignoring unsupported options: security_opt

service stack-data-uploader: config not found: TEST_geoserver
```

and when checking the `stack-manager` logs I can see that there are issues with uploading Ontop (for whatever reason):
```
Exception in thread "main" java.lang.RuntimeException: Failed to write out combined Ontop mapping file '/ontop.obda'.
        at com.cmclinnovations.stack.clients.ontop.OntopClient.updateOBDA(OntopClient.java:77)
        at com.cmclinnovations.stack.services.OntopService.doPostStartUpConfiguration(OntopService.java:71)
        at com.cmclinnovations.stack.services.DockerService.doPostStartUpConfiguration(DockerService.java:220)
        at com.cmclinnovations.stack.services.ServiceManager.initialiseService(ServiceManager.java:114)
        at com.cmclinnovations.stack.Stack.<init>(Stack.java:30)
        at com.cmclinnovations.stack.App.main(App.java:24)
Caused by: java.io.IOException: Error while saving the OBDA model to the file located at /tmp/ontop5433291818223829511.obda.
Make sure you have the write permission at the location specified.
        at it.unibz.inf.ontop.spec.mapping.serializer.impl.OntopNativeMappingSerializer.write(OntopNativeMappingSerializer.java:44)
        at com.cmclinnovations.stack.clients.ontop.SQLPPMappingImplementation.serialize(SQLPPMappingImplementation.java:113)
        at com.cmclinnovations.stack.clients.ontop.OntopClient.updateOBDA(OntopClient.java:69)
        ... 5 more
```

**Comment by markushofmeister** [comment]
I am able to spin up the stack using the stack-manager both on my local machine as well as on Digital Ocean. The permission issues seem resolved. I am also able to upload both triple and quad rdf data while getting the expected number of instantiated triples. Two minor suggestions:

1) Currently the example config files contain `"com.bigdata.rdf.store.AbstractTripleStore.triplesMode":true` and `"com.bigdata.rdf.store.AbstractTripleStore.quadsMode": true` for triple and quad upload, respectively. I believe (and tested) that `"com.bigdata.rdf.store.AbstractTripleStore.quadsMode":` with `true` and `false` would be a more consistent way to handle this.

2) As quad uploads require `"com.bigdata.rdf.sail.truthMaintenance": false` in the config file, I suggest we keep this (potentially unnecessary) setting also for triples. This might simplify things and avoid potential issues where people start to amend there local triple upload files to upload quads.

Please view both comments as suggestions.

**Review by markushofmeister — APPROVED** [review]
I have tested both uploading rdf data (triples and quads) and executing larger queries which previously failed due to nginx memory limitation. I can confirm that both works now.
For the rdf upload please see my suggestions in the comment above.

**Review by cmclscourtney — APPROVED** [review]
tested and worked for me

**Comment by gpeb2** [comment]
> I am able to spin up the stack using the stack-manager both on my local machine as well as on Digital Ocean. The permission issues seem resolved. I am also able to upload both triple and quad rdf data while getting the expected number of instantiated triples. Two minor suggestions:
> 
> 1. Currently the example config files contain `"com.bigdata.rdf.store.AbstractTripleStore.triplesMode":true` and `"com.bigdata.rdf.store.AbstractTripleStore.quadsMode": true` for triple and quad upload, respectively. I believe (and tested) that `"com.bigdata.rdf.store.AbstractTripleStore.quadsMode":` with `true` and `false` would be a more consistent way to handle this.

I agree that it looks like setting `...triplesMode": true`, `...quadsMode": false` or neither of them generates the same namespace but I think sticking with `triplesMode` and `quadsMode` is better as there is also a `triplesModeWithProvenance` property and just using `true`/`false` with the `quadsMode` property suggests a false dichotomy.
> 2. As quad uploads require `"com.bigdata.rdf.sail.truthMaintenance": false` in the config file, I suggest we keep this (potentially unnecessary) setting also for triples. This might simplify things and avoid potential issues where people start to amend there local triple upload files to upload quads.

I've rejigged the examples to reduce potential confusion whilst still showing a range of possibilities (see commit dc38018).
> 
> Please view both comments as suggestions.

**Pull request merged**
