### PR TITLE
1012 fia caches enforcedendpoint

### PR DESCRIPTION
**Pull request by cmclscourtney**
See #1012 for bug fixed.

In effort to work through the code and play around also added some small bits of Jackson serialization. I think the `Optional` is useful for the endpoint specification and will make maintenance in the future easier.

### CODE REVIEW

**Review by mdhillman — APPROVED** [review]
Changes all look good to me.

**Comment by cmclscourtney** [comment]
@kok-foong just wondering if this resolves #1012?

**Comment by kok-foong** [comment]
> @kok-foong just wondering if this resolves #1012?

is 3.0.1-SNAPSHOT the version to test? It seems that it's still caching the value to me

**Comment by kok-foong** [comment]
> > @kok-foong just wondering if this resolves #1012?
> 
> is 3.0.1-SNAPSHOT the version to test? It seems that it's still caching the value to me

I suspect the latest image does not correspond to the latest code

**Comment by cmclscourtney** [comment]
> > > @kok-foong just wondering if this resolves #1012?
> > 
> > 
> > is 3.0.1-SNAPSHOT the version to test? It seems that it's still caching the value to me
> 
> I suspect the latest image does not correspond to the latest code

The version is `3.0.1-1012-SNAPSHOT`

**Review by kok-foong — APPROVED** [review]
Tested and can confirm FIA no longer caches the endpoint

**Pull request merged**
