### PR TITLE
1161 dev gas grid input agent

### PR DESCRIPTION
**Pull request by markushofmeister**
Updated storage and retrieval scripts of instantaneous gas flow data to use latest time series implementation. Also included respective unit tests and dockerised integration tests for SPARQL queries.

### CODE REVIEW

**Comment by markushofmeister** [comment]
> This PR has been left _far_ too long, which is my own fault. I have now merged from main back into this branch, can @markushofmeister give that merge a quick glance to check that it doesn't ruin anything? If it doesn't then I will approve and merge this PR.

As @msff2 took my work over and forward, I suggest that he gives it a final review. I believe he should have the best understanding of what the agent should do

**Comment by markushofmeister** [comment]
> > This PR has been left _far_ too long, which is my own fault. I have now merged from main back into this branch, can @markushofmeister give that merge a quick glance to check that it doesn't ruin anything? If it doesn't then I will approve and merge this PR.
> 
> As @msff2 took my work over and forward, I suggest that he gives it a final review. I believe he should have the best understanding of what the agent should do

@msff2: Are you taking this forward by any chance?

**Comment by markushofmeister** [comment]
> > > This PR has been left _far_ too long, which is my own fault. I have now merged from main back into this branch, can @markushofmeister give that merge a quick glance to check that it doesn't ruin anything? If it doesn't then I will approve and merge this PR.
> > 
> > 
> > As @msff2 took my work over and forward, I suggest that he gives it a final review. I believe he should have the best understanding of what the agent should do
> 
> @msff2: Are you taking this forward by any chance?

@msff2: What is our strategy with this branch at the moment?

**Review by msff2 — APPROVED** [review]
I merged "main" into this branch and resolved conflicts in the pom file. The goal of this branch was to integrate the DTVF visualisation framework into the gas grid agent. I completed the task long ago, but the merging was not done, so I see no problem completing the merge.

**Pull request merged**
