### PR TITLE
Dev agent routing

### PR DESCRIPTION
**Pull request by csl37**

### CODE REVIEW

**Comment by csl37** [comment]
CachedRouter

**Comment by csl37** [comment]
Pending creation of ontoagent triple store 

**To do before merge**: update version number

**Review by sm453 — APPROVED** [review]
In AgentRouter.getQuery, getting the agent URL by filtering the agent name out of its IRI string is a bit of a disaster. Trying to extract semantics out of an IRI is kind of the cardinal sin of the semantic web, but I'm guessing this is simply a symptom of the inadequacy of OntoAgent, right? If so, then I wouldn't try to improve this here, because solving problems with OntoAgent is clearly out of scope of this PR.

**Comment by csl37** [comment]
> In AgentRouter.getQuery, getting the agent URL by filtering the agent name out of its IRI string is a bit of a disaster. Trying to extract semantics out of an IRI is kind of the cardinal sin of the semantic web, but I'm guessing this is simply a symptom of the inadequacy of OntoAgent, right? If so, then I wouldn't try to improve this here, because solving problems with OntoAgent is clearly out of scope of this PR.

Correct. I think we would need to extend the ontology to include a label -- similar to ontokgrouter.

**Pull request merged**
