### PR TITLE
1777 dev update osm agent matching iteration

### PR DESCRIPTION
**Pull request by YiKaiTsai**

### CODE REVIEW

**Comment by kok-foong** [comment]
Have you tested this?

**Comment by YiKaiTsai** [comment]
> Have you tested this?

Yes. Tested on the Pirmasens dataset, and compared it to the results from 1.5.0, same number of OSM geometries matched.

**Comment by kok-foong** [comment]
what about speed and performance?

**Comment by YiKaiTsai** [comment]
> what about speed and performance?

I thought this update was so that the OSM agent could run in the background while not taking up most of the memory, and that the speed was not being considered.

**Comment by kok-foong** [comment]
yes, have you observed that the memory usage is lower?

**Comment by YiKaiTsai** [comment]
> yes, have you observed that the memory usage is lower?

Yes.

**Review by kok-foong — APPROVED** [review]

**Pull request merged**
